### ISSUE TITLE
Example of posting images in a post submit call?

### ISSUE THREAD

**Issue by ishields** [Nakilon/reddit_bot#22]
Hello! Love this gem! I'm looking to send an image url when using the post submit call. Are there any examples of this?

Currently doing something like this:
`
bot.json :post, '/api/submit', { sr: subreddit_name, kind: 'self', title: title, text: message, url: url }
`
But would like to also send {image_url: 'http://example/myimage.jpg'} and have that be used as the posts image.
Any ideas on how this could be done or in what example I should look?

**Comment by Nakilon** [comment]
Oh I wish Github was sending email notifications on new Issues. I had no idea about this.

Doesn't this work for you? https://github.com/Nakilon/reddit_bot/blob/3f28eeb5b6396f1df149fcb4a52043fc3658b5f4/examples/largeimages/main.rb#L145-L152
I.e. remove `text`, change the `kind` to `link`. Or am I missing something?
